---
abstract: 'Dist::Zilla Mixed Up'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Zilla-Dist
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  Dist::Zilla: '0'
  File::Share: '0'
  Hash::Merge: '0'
  IO::All: '0'
  Swim: v0.0.7
  Template::Toolkit::Simple: '0'
  YAML::XS: '0'
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/zilla-dist-pm/issues
  homepage: https://github.com/ingydotnet/zilla-dist-pm
  repository: https://github.com/ingydotnet/zilla-dist-pm.git
version: 0.0.41
