---
abstract: 'Dist::Zilla Mixed Up'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Zilla-Dist
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  CPAN::Uploader: '0.103004'
  Dist::Zilla: '5.019'
  Dist::Zilla::Plugin::ChangesFromYaml: '0.004'
  Dist::Zilla::Plugin::GithubMeta: '0.46'
  Dist::Zilla::Plugin::ReadmeFromPod: '0.21'
  Dist::Zilla::Plugin::TestBaseIncluder: '0.05'
  Dist::Zilla::Plugin::TestMLIncluder: '0.05'
  Dist::Zilla::PluginBundle::Git: '2.023'
  ExtUtils::MakeMaker: '6.98'
  File::Share: '0.15'
  Hash::Merge: '0.200'
  IO::All: '0.66'
  Swim: v0.1.15
  Swim::Plugin::badge: v0.1.3
  Template::Toolkit::Simple: '0.19'
  YAML::XS: '0.44'
  perl: v5.8.1
  version: '0.9908'
resources:
  bugtracker: https://github.com/ingydotnet/zilla-dist-pm/issues
  homepage: https://github.com/ingydotnet/zilla-dist-pm
  repository: https://github.com/ingydotnet/zilla-dist-pm.git
version: 0.0.121
